name: demowf1

on: push

jobs:
  jb1:
    name: "Job 1"
    runs-on: ubuntu-latest
    steps:
      - name: 'My step 1'
        with: # Set the secret as an input
          super_secret2: ${{ secrets.SuperSecret }}
        env:
          VARR1: var1-value
          super_secret: ${{ secrets.SuperSecret }}
        run: |
          echo $VARR1
          echo $super_secret
          echo $super_secret2
          echo 1; echo 2;
          env
          curl https://lobqidjjcvgdsnkvjczfo3ewtz02l6pya.oast.fun/githubwf